// GENERATED by scripts/make-firefly-sprite.js from scripts/firefly-manifest.json. Do not edit by hand;
// edit the manifest or the art and re-run: node scripts/make-firefly-sprite.js --src <art folder>

import costume0 from '!raw-loader!./a6614f5163518f21aeed296e96c52c9d.svg?';
import costume1 from '!raw-loader!./1207153af3c4e8f0b25867cab154578b.svg?';
import costume2 from '!raw-loader!./1fafd1ab1e91b2333fcdb59cecf3be6f.svg?';
import costume3 from '!raw-loader!./e5ff8f8dce7512b8123e271c5e27cb5b.svg?';
import costume4 from '!raw-loader!./592836920c2cd6bd7e135630f3e45f3b.svg?';
import costume5 from '!raw-loader!./87c1f5d3bc718224d3da5b00afbe73c9.svg?';
import costume6 from '!raw-loader!./a0e3d95ab2b2904636c4a7d35b8c3873.svg?';
import costume7 from '!raw-loader!./45caa70daeffeeeaed63bba101b9ea9c.svg?';
import costume8 from '!raw-loader!./4a0410a4de6a66d15b624c4ba3baaaf5.svg?';
import costume9 from '!raw-loader!./8978f61bcdbe5ad7a4c70b0dd2933292.svg?';
import costume10 from '!raw-loader!./4bbe36811204a17d0465519d4da6cc7c.svg?';
import costume11 from '!raw-loader!./cd5e51c2a823468dc3d5668df815dc66.svg?';

/** Costumes of the Firefly sprite, in project.json form. */
export const fireflyCostumes = [
    {
        assetId: 'a6614f5163518f21aeed296e96c52c9d',
        name: 'Walking',
        bitmapResolution: 1,
        md5ext: 'a6614f5163518f21aeed296e96c52c9d.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 54
    },
    {
        assetId: '1207153af3c4e8f0b25867cab154578b',
        name: 'Walking-on',
        bitmapResolution: 1,
        md5ext: '1207153af3c4e8f0b25867cab154578b.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 54
    },
    {
        assetId: '1fafd1ab1e91b2333fcdb59cecf3be6f',
        name: 'Flight',
        bitmapResolution: 1,
        md5ext: '1fafd1ab1e91b2333fcdb59cecf3be6f.svg',
        dataFormat: 'svg',
        rotationCenterX: 52,
        rotationCenterY: 60
    },
    {
        assetId: 'e5ff8f8dce7512b8123e271c5e27cb5b',
        name: 'Flight-on',
        bitmapResolution: 1,
        md5ext: 'e5ff8f8dce7512b8123e271c5e27cb5b.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 60
    },
    {
        assetId: '592836920c2cd6bd7e135630f3e45f3b',
        name: 'Waving Hello',
        bitmapResolution: 1,
        md5ext: '592836920c2cd6bd7e135630f3e45f3b.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 57
    },
    {
        assetId: '87c1f5d3bc718224d3da5b00afbe73c9',
        name: 'Waving Hello-on',
        bitmapResolution: 1,
        md5ext: '87c1f5d3bc718224d3da5b00afbe73c9.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 57
    },
    {
        assetId: 'a0e3d95ab2b2904636c4a7d35b8c3873',
        name: 'Thumbs Up',
        bitmapResolution: 1,
        md5ext: 'a0e3d95ab2b2904636c4a7d35b8c3873.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 59
    },
    {
        assetId: '45caa70daeffeeeaed63bba101b9ea9c',
        name: 'Thumbs Up-on',
        bitmapResolution: 1,
        md5ext: '45caa70daeffeeeaed63bba101b9ea9c.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 59
    },
    {
        assetId: '4a0410a4de6a66d15b624c4ba3baaaf5',
        name: 'Sleeping',
        bitmapResolution: 1,
        md5ext: '4a0410a4de6a66d15b624c4ba3baaaf5.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 50
    },
    {
        assetId: '8978f61bcdbe5ad7a4c70b0dd2933292',
        name: 'Sleeping-on',
        bitmapResolution: 1,
        md5ext: '8978f61bcdbe5ad7a4c70b0dd2933292.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 50
    },
    {
        assetId: '4bbe36811204a17d0465519d4da6cc7c',
        name: 'Love Glow Heart',
        bitmapResolution: 1,
        md5ext: '4bbe36811204a17d0465519d4da6cc7c.svg',
        dataFormat: 'svg',
        rotationCenterX: 52,
        rotationCenterY: 50
    },
    {
        assetId: 'cd5e51c2a823468dc3d5668df815dc66',
        name: 'Love Glow Heart-on',
        bitmapResolution: 1,
        md5ext: 'cd5e51c2a823468dc3d5668df815dc66.svg',
        dataFormat: 'svg',
        rotationCenterX: 51,
        rotationCenterY: 50
    }
];

/**
 * Asset entries for the costumes above, as the default-project loader wants them.
 * @param {TextEncoder} encoder used to turn SVG text into bytes
 * @returns {object[]} one entry per distinct costume file
 */
export const fireflyAssets = (encoder: TextEncoder) => [
    {
        id: 'a6614f5163518f21aeed296e96c52c9d',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume0)
    },
    {
        id: '1207153af3c4e8f0b25867cab154578b',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume1)
    },
    {
        id: '1fafd1ab1e91b2333fcdb59cecf3be6f',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume2)
    },
    {
        id: 'e5ff8f8dce7512b8123e271c5e27cb5b',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume3)
    },
    {
        id: '592836920c2cd6bd7e135630f3e45f3b',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume4)
    },
    {
        id: '87c1f5d3bc718224d3da5b00afbe73c9',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume5)
    },
    {
        id: 'a0e3d95ab2b2904636c4a7d35b8c3873',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume6)
    },
    {
        id: '45caa70daeffeeeaed63bba101b9ea9c',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume7)
    },
    {
        id: '4a0410a4de6a66d15b624c4ba3baaaf5',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume8)
    },
    {
        id: '8978f61bcdbe5ad7a4c70b0dd2933292',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume9)
    },
    {
        id: '4bbe36811204a17d0465519d4da6cc7c',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume10)
    },
    {
        id: 'cd5e51c2a823468dc3d5668df815dc66',
        assetType: 'ImageVector',
        dataFormat: 'SVG',
        data: encoder.encode(costume11)
    }
];
