// GENERATED by scripts/make-firefly-sprite.js from scripts/firefly-manifest.json. Do not edit by hand;
// edit the manifest or the art and re-run: node scripts/make-firefly-sprite.js --src <art folder>

import costume0 from '!arraybuffer-loader!./6c6e1790341353e36edfd13f640dba03.png?';
import costume1 from '!arraybuffer-loader!./7e992800f69e0ee2ec0ddf67cf937ded.png?';
import costume2 from '!arraybuffer-loader!./0ce6ff0d2836ad9a8a41f8a1d7a7c6ff.png?';
import costume3 from '!arraybuffer-loader!./0dcc125d7200c4aa89425eea2887d8e3.png?';
import costume4 from '!arraybuffer-loader!./0e2a052bcef6c80dabab57c08a3e80e3.png?';
import costume5 from '!arraybuffer-loader!./1092d47d90fc47ddc9c6f63b918033b2.png?';
import costume6 from '!arraybuffer-loader!./7a20225548108dfeaddf4603e36ad2f3.png?';
import costume7 from '!arraybuffer-loader!./db2551c7c72e5faa4e8491570fabc3c9.png?';
import costume8 from '!arraybuffer-loader!./b5a814a2ef29c7f1c16aedeb6a7863f0.png?';
import costume9 from '!arraybuffer-loader!./8b97ecff386edba17a940fe06b629585.png?';
import costume10 from '!arraybuffer-loader!./aa0a5e9fcd1f8b2810e6e2da142021fe.png?';
import costume11 from '!arraybuffer-loader!./d068af204392b502f8eae04b6a2d9213.png?';

/** Costumes of the Firefly sprite, in project.json form. */
export const fireflyCostumes = [
    {
        assetId: '6c6e1790341353e36edfd13f640dba03',
        name: 'Walking',
        bitmapResolution: 1,
        md5ext: '6c6e1790341353e36edfd13f640dba03.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: '7e992800f69e0ee2ec0ddf67cf937ded',
        name: 'Walking-on',
        bitmapResolution: 1,
        md5ext: '7e992800f69e0ee2ec0ddf67cf937ded.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: '0ce6ff0d2836ad9a8a41f8a1d7a7c6ff',
        name: 'Flight',
        bitmapResolution: 2,
        md5ext: '0ce6ff0d2836ad9a8a41f8a1d7a7c6ff.png',
        dataFormat: 'png',
        rotationCenterX: 104,
        rotationCenterY: 119
    },
    {
        assetId: '0dcc125d7200c4aa89425eea2887d8e3',
        name: 'Flight-on',
        bitmapResolution: 2,
        md5ext: '0dcc125d7200c4aa89425eea2887d8e3.png',
        dataFormat: 'png',
        rotationCenterX: 102,
        rotationCenterY: 119
    },
    {
        assetId: '0e2a052bcef6c80dabab57c08a3e80e3',
        name: 'Waving Hello',
        bitmapResolution: 1,
        md5ext: '0e2a052bcef6c80dabab57c08a3e80e3.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: '1092d47d90fc47ddc9c6f63b918033b2',
        name: 'Waving Hello-on',
        bitmapResolution: 1,
        md5ext: '1092d47d90fc47ddc9c6f63b918033b2.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: '7a20225548108dfeaddf4603e36ad2f3',
        name: 'Thumbs Up',
        bitmapResolution: 1,
        md5ext: '7a20225548108dfeaddf4603e36ad2f3.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: 'db2551c7c72e5faa4e8491570fabc3c9',
        name: 'Thumbs Up-on',
        bitmapResolution: 1,
        md5ext: 'db2551c7c72e5faa4e8491570fabc3c9.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: 'b5a814a2ef29c7f1c16aedeb6a7863f0',
        name: 'Sleeping',
        bitmapResolution: 1,
        md5ext: 'b5a814a2ef29c7f1c16aedeb6a7863f0.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: '8b97ecff386edba17a940fe06b629585',
        name: 'Sleeping-on',
        bitmapResolution: 1,
        md5ext: '8b97ecff386edba17a940fe06b629585.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: 'aa0a5e9fcd1f8b2810e6e2da142021fe',
        name: 'Love Glow Heart',
        bitmapResolution: 1,
        md5ext: 'aa0a5e9fcd1f8b2810e6e2da142021fe.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    },
    {
        assetId: 'd068af204392b502f8eae04b6a2d9213',
        name: 'Love Glow Heart-on',
        bitmapResolution: 1,
        md5ext: 'd068af204392b502f8eae04b6a2d9213.png',
        dataFormat: 'png',
        rotationCenterX: 54,
        rotationCenterY: 53
    }
];

/**
 * Asset entries for the costumes above, as the default-project loader wants them.
 * @param {TextEncoder} encoder used to turn SVG text into bytes
 * @returns {object[]} one entry per distinct costume file
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const fireflyAssets = (encoder: TextEncoder) => [
    {
        id: '6c6e1790341353e36edfd13f640dba03',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume0)
    },
    {
        id: '7e992800f69e0ee2ec0ddf67cf937ded',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume1)
    },
    {
        id: '0ce6ff0d2836ad9a8a41f8a1d7a7c6ff',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume2)
    },
    {
        id: '0dcc125d7200c4aa89425eea2887d8e3',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume3)
    },
    {
        id: '0e2a052bcef6c80dabab57c08a3e80e3',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume4)
    },
    {
        id: '1092d47d90fc47ddc9c6f63b918033b2',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume5)
    },
    {
        id: '7a20225548108dfeaddf4603e36ad2f3',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume6)
    },
    {
        id: 'db2551c7c72e5faa4e8491570fabc3c9',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume7)
    },
    {
        id: 'b5a814a2ef29c7f1c16aedeb6a7863f0',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume8)
    },
    {
        id: '8b97ecff386edba17a940fe06b629585',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume9)
    },
    {
        id: 'aa0a5e9fcd1f8b2810e6e2da142021fe',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume10)
    },
    {
        id: 'd068af204392b502f8eae04b6a2d9213',
        assetType: 'ImageBitmap',
        dataFormat: 'PNG',
        data: new Uint8Array(costume11)
    }
];
